# Generated by Django 4.2.10 on 2024-02-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_event_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="hash",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
